// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wailsupdate$0 from "../../pkg/wailsupdate/models.js";

/**
 * @returns {$CancellablePromise<wailsupdate$0.ActionResponse>}
 */
export function ApplyPending() {
    return $Call.ByID(2857970655).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<wailsupdate$0.CheckResponse>}
 */
export function CheckNow() {
    return $Call.ByID(3792226688).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<wailsupdate$0.State>}
 */
export function GetState() {
    return $Call.ByID(1020347649).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<wailsupdate$0.ActionResponse>}
 */
export function Restart() {
    return $Call.ByID(3205679179).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = wailsupdate$0.ActionResponse.createFrom;
const $$createType1 = wailsupdate$0.CheckResponse.createFrom;
const $$createType2 = wailsupdate$0.State.createFrom;
