// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ActionResponse {
    /**
     * Creates a new ActionResponse instance.
     * @param {Partial<ActionResponse>} [$$source = {}] - The source object to create the ActionResponse.
     */
    constructor($$source = {}) {
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startedAt"] = "";
        }
        if (!("applied" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["applied"] = false;
        }
        if (!("restarted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["restarted"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActionResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActionResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActionResponse(/** @type {Partial<ActionResponse>} */($$parsedSource));
    }
}

export class CheckResponse {
    /**
     * Creates a new CheckResponse instance.
     * @param {Partial<CheckResponse>} [$$source = {}] - The source object to create the CheckResponse.
     */
    constructor($$source = {}) {
        if (!("checkedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checkedAt"] = "";
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {UpdateView | null | undefined}
             */
            this["update"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CheckResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("update" in $$parsedSource) {
            $$parsedSource["update"] = $$createField2_0($$parsedSource["update"]);
        }
        return new CheckResponse(/** @type {Partial<CheckResponse>} */($$parsedSource));
    }
}

export class State {
    /**
     * Creates a new State instance.
     * @param {Partial<State>} [$$source = {}] - The source object to create the State.
     */
    constructor($$source = {}) {
        if (!("manifestURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["manifestURL"] = "";
        }
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["currentHash"] = undefined;
        }
        if (!("channel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["channel"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["nativeCompat"] = undefined;
        }
        if (!("targetPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetPath"] = "";
        }
        if (!("tempDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tempDir"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastCheckedAt"] = undefined;
        }
        if (!("pendingRestart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pendingRestart"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {UpdateView | null | undefined}
             */
            this["availableUpdate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["metadata"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["notes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {State}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType1;
        const $$createField10_0 = $$createType2;
        const $$createField11_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("availableUpdate" in $$parsedSource) {
            $$parsedSource["availableUpdate"] = $$createField9_0($$parsedSource["availableUpdate"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField10_0($$parsedSource["metadata"]);
        }
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField11_0($$parsedSource["notes"]);
        }
        return new State(/** @type {Partial<State>} */($$parsedSource));
    }
}

export class UpdateView {
    /**
     * Creates a new UpdateView instance.
     * @param {Partial<UpdateView>} [$$source = {}] - The source object to create the UpdateView.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("channel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["channel"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["releaseNotes"] = undefined;
        }
        if (!("mandatory" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mandatory"] = false;
        }
        if (!("artifactURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifactURL"] = "";
        }
        if (!("artifactHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifactHash"] = "";
        }
        if (!("artifactSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["artifactSize"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["deltaURL"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["deltaHash"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["deltaSize"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["deltaFromHash"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateView(/** @type {Partial<UpdateView>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = UpdateView.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
