// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../Eriyc/wailsrel/examples/authenticated-http-app/models.js";

declare module "/wails/runtime.js" {
    namespace Events {
        interface CustomEvents {
            "update:available": main$0.updateView;
            "update:log": main$0.logEvent;
            "update:progress": main$0.progressEvent;
        }
    }
}
